/** @type {import('tailwindcss').Config} */
export default {
  content: ["./index.html", "./src/**/*.{js,ts,jsx,tsx}"],
  theme: {
    extend: {
      screens: {
        xs: "320px",
        sm: "480px",
        md: "700px",
        lg: "1024px",
        xl: "1280px",
        "2xl": "1440px",
        "3xl": "1536px",
        "4xl": "2000px",
      },
      colors: {
        primaryBlue: "#407BFF",
        primaryBlack: "#1D2939",
        secondaryBlack: "#667085",
        lightBlack: "#333333",
        bg_active: "rgba(28, 63, 148, 0.05)",
        secondaryGray: "#98A2B3",
        deepBlack: "#333",
        primaryWhite: "#FAFAFC",
        "grey-00": "#758494",
        "grey-02": "#DDDDDD",
        "Grey-modern": "#FCFCFD",
        "custom-grey": "rgba(64, 123, 255, 0.10)",
        "solid-black": "#041549",
        "grey-700": "#344054",
        "secondary-white": "#F7F8FF",
        "grey-300": "#D0D5DD",
        "grey-500": "#667085",
        "eye-icon-color": "rgba(4, 21, 73, 1)",
      },
      boxShadow: {
        disabled: "0px 8px 26.85px 0px rgba(47, 46, 65, 0.35)",
        "active-shadow": "0px 8px 26.85px 0px rgba(64, 123, 255, 0.35)",
        "card-shadow": "0px 24px 32px -3px rgba(3, 9, 50, 0.04)",
        "close-shadow": "0px 3px 20px 0px rgba(0, 0, 0, 0.06)",
        "towing-card-shadow": "0px 10px 25px 0px rgba(151, 143, 175, 0.04)",
        "next-btn": "0px 8px 26.85px 0px rgba(16, 138, 0, 0.35)",
        fields: "0px 1px 2px 0px rgba(16, 24, 40, 0.05)",
      },
      fontFamily: {
        "fellix-semibold-italic": ["Fellix-SemiBoldItalic", "sans"],
        "fellix-semibold": ["Fellix-SemiBold", "sans"],
        "fellix-light": ["Fellix-Light", "sans"],
        "fellix-black": ["Fellix-Black", "sans"],
        "fellix-black-italic": ["Fellix-BlackItalic", "sans"],
        "fellix-extra-bold": ["Fellix-ExtraBold", "sans"],
        "fellix-thin-italic": ["Fellix-ThinItalic", "sans"],
        "fellix-medium": ["Fellix-Medium", "sans"],
        "fellix-light-italic": ["Fellix-LightItalic", "sans"],
        "fellix-bold-italic": ["Fellix-BoldItalic", "sans"],
        "fellix-thin": ["Fellix-Thin", "sans"],
        "fellix-regular": ["Fellix-Regular", "sans"],
        "fellix-bold": ["Fellix-Bold", "sans"],
        "fellix-regular-italic": ["Fellix-RegularItalic", "sans"],
        "fellix-extra-bold-italic": ["Fellix-ExtraBoldItalic", "sans"],
        "fellix-medium-italic": ["Fellix-MediumItalic", "sans"],
      },
    },
  },
  plugins: [],
};
